services:
  mysql:
    image: mysql:8.0
    container_name: school_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_db
      MYSQL_USER: pritija_user
      MYSQL_PASSWORD: nibi@0852
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - school_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: school_app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: pritija_user
      DB_PASS: nibi@0852
      DB_NAME: school_db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/app
    networks:
      - school_network

volumes:
  mysql_data:

networks:
  school_network:
