version: '3.8'

services:
  # MySQL Database Service (same as production)
  mysql:
    image: mysql:8.0
    container_name: school_mysql_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_db
      MYSQL_USER: pritija_user
      MYSQL_PASSWORD: nibi@0852
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - school_network

  # Node.js Application Service for Development
  app:
    build: .
    container_name: school_app_dev
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: mysql
      DB_USER: pritija_user
      DB_PASS: nibi@0852
      DB_NAME: school_db
      PORT: 3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - school_network
    command: npm run dev

volumes:
  mysql_dev_data:

networks:
  school_network:
    driver: bridge
